baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'


[menu]

[[menu.main]]
	name = 'whoami'
	pageRef = '/content/aboutme/'
	weight = 1


[[menu.main]]
	name = 'Blog'
	pageRef = '/content/posts/'
	weight = 2


[[menu.main]]
	name = 'Projects/CTFs'
	pageRef = '/content/ctfs/'
	weight = 3
