baseURL = 'https://rtgthedestroyer.github.io/pwn-blog/'
languageCode = 'en-us'
title = 'pwn-blog'
theme = 'hugo-theme-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'


[menu]
[[menu.main]]
	name = 'whoami'
	pageRef = '/aboutme/'
	weight = 1


[[menu.main]]
	name = 'Blog'
	pageRef = '/posts/'
	weight = 2


[[menu.main]]
	name = 'Projects/CTFs'
	pageRef = '/ctfs/'
	weight = 3
